#cloud-config
packages:
    - docker.io
package_reboot_if_required: true
swap:
    filename: /swapfile
    size: 4294967296
runcmd:
  - curl -L --fail https://github.com/docker/compose/releases/download/1.29.2/run.sh -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
